# Server configuration
server:
  port: 8088
  
# JPA configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gira
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
      
logging:
  level:
    root: info
    org.springframework: debug
    '[cybersoft.javabackend.java11.gira]': debug
  pattern:
    
    dateformat: 
  
      
gira:    
   app:
     jwt-secret: cybersoftgiraapplication
     jwt-duration: 86400000
   
    
     